from core.enums.enum_str import EnumStr


class LandmarksManMadeInfrastructureMastsTowers(EnumStr):
    BUNKER_OSMCARTO = 'bunker_osmcarto'
    CHIMNEY = 'chimney'
    COLUMN = 'column'
    COMMUNICATION_TOWER = 'communication_tower'
    CRANE = 'crane'
    CROSS = 'cross'
    GENERATOR_WIND = 'generator_wind'
    HUNTING_STAND = 'hunting_stand'
    LIGHTHOUSE = 'lighthouse'
    MAST_COMMUNICATIONS = 'mast_communications'
    MAST_GENERAL = 'mast_general'
    MAST_LIGHTING = 'mast_lighting'
    STORAGE_TANK = 'storage_tank'
    TELESCOPE_DISH = 'telescope_dish'
    TELESCOPE_DOME = 'telescope_dome'
    TOWER_BELL_TOWER = 'tower_bell_tower'
    TOWER_CANTILEVER_COMMUNICATION = 'tower_cantilever_communication'
    TOWER_COOLING = 'tower_cooling'
    TOWER_DEFENSIVE = 'tower_defensive'
    TOWER_DISH = 'tower_dish'
    TOWER_DOME = 'tower_dome'
    TOWER_FREESTANDING = 'tower_freestanding'
    TOWER_LATTICE = 'tower_lattice'
    TOWER_LATTICE_COMMUNICATION = 'tower_lattice_communication'
    TOWER_LATTICE_LIGHTING = 'tower_lattice_lighting'
    TOWER_LIGHTING = 'tower_lighting'
    TOWER_OBSERVATION = 'tower_observation'
    WATER_TOWER = 'water_tower'
    WINDMILL = 'windmill'
