from core.enums.enum_str import EnumStr


class Nature(EnumStr):
    AREA_BEACH_GRAVEL = 'area_beach_gravel'
    AREA_BEACH_SAND = 'area_beach_sand'
    AREA_NATURAL_BEACH = 'area_natural_beach'
    AREA_NATURAL_HEATH_YELLOW = 'area_natural_heath_yellow'
    AREA_NATURAL_MARSH = 'area_natural_marsh'
    AREA_NATURAL_SCRUB = 'area_natural_scrub'
    AREA_NATURAL_WOOD = 'area_natural_wood'
    AREA_SAND = 'area_sand'
    BARE_ROCK = 'bare_rock'
    BASE_LAYER_LAND = 'base_layer_land'
    BASE_LAYER_WATER = 'base_layer_water'
    GLACIER_AREA = 'glacier_area'
    LANDUSE_SALT_POND = 'landuse_salt_pond'
    LEAFTYPE_BROADLEAVED = 'leaftype_broadleaved'
    LEAFTYPE_LEAFLESS = 'leaftype_leafless'
    LEAFTYPE_MIXED = 'leaftype_mixed'
    LEAFTYPE_NEEDLELEAVED = 'leaftype_needleleaved'
    NATURAL_GRASSLAND = 'natural_grassland'
    NATURAL_MUD_MAPNIK = 'natural_mud_mapnik'
    NATURAL_REEF = 'natural_reef'
    NATURAL_WETLAND_BOG = 'natural_wetland_bog'
    NATURAL_WETLAND_MANGROVE = 'natural_wetland_mangrove'
    NATURAL_WETLAND_MARSH = 'natural_wetland_marsh'
    NATURAL_WETLAND_REED = 'natural_wetland_reed'
    NATURAL_WETLAND_SWAMP = 'natural_wetland_swamp'
    NATURAL_WETLAND_WATER = 'natural_wetland_water'
    SALTMARSH_WATER = 'saltmarsh_water'
    SCREE = 'scree'
    WATER_INTERMITTENT = 'water_intermittent'
