from core.enums.enum_str import EnumStr


class Attraction(EnumStr):
    # https://wiki.openstreetmap.org/wiki/Key:attraction
    ALPINE_COASTER = 'alpine_coaster'
    AMUSEMENT_RIDE = 'amusement_ride'
    ANIMAL = 'animal'
    BALLOON_RIDE = 'balloon_ride'
    BIG_WHEEL = 'big_wheel'
    BOAT_RIDE = 'boat_ride'
    BOXER = 'boxer'
    BUMPER_BOAT = 'bumper_boat'
    BUMPER_CAR = 'bumper_car'
    BUNGEE_JUMPING = 'bungee_jumping'
    CAROUSEL = 'carousel'
    DARK_RIDE = 'dark_ride'
    DROP_TOWER = 'drop_tower'
    FORMAL_GARDEN = 'formal_garden'
    GAME_INSTALLATION = 'game_installation'
    HAUNTED_HOUSE = 'haunted_house'
    HISTORIC = 'historic'
    JET = 'jet'
    KIDDIE_RIDE = 'kiddie_ride'
    LAZY_RIVER = 'lazy_river'
    LOG_FLUME = 'log_flume'
    MAZE = 'maze'
    MECHANICAL_BULL = 'mechanical_bull'
    PARASAILING = 'parasailing'
    PENDULUM_RIDE = 'pendulum_ride'
    PIRATE_SHIP = 'pirate_ship'
    RIVER_RAFTING = 'river_rafting'
    ROCK_ART = 'rock_art'
    ROLLER_COASTER = 'roller_coaster'
    SEAPLANE_RIDE = 'seaplane_ride'
    SLIDE = 'slide'
    SUMMER_TOBOGGAN = 'summer_toboggan'
    SWING_CAROUSEL = 'swing_carousel'
    TEACUP = 'teacup'
    TRAIN = 'train'
    WATER_SLIDE = 'water_slide'
