from core.enums.enum_str import EnumStr


class Barrier(EnumStr):
    # https://wiki.openstreetmap.org/wiki/Key:barrier
    BLOCK = 'block'
    BOLLARD = 'bollard'
    BORDER_CONTROL = 'border_control'
    BUMP_GATE = 'bump_gate'
    BUS_TRAP = 'bus_trap'
    CABLE_BARRIER = 'cable_barrier'
    CATTLE_GRID = 'cattle_grid'
    CHAIN = 'chain'
    CITY_WALL = 'city_wall'
    CYCLE_BARRIER = 'cycle_barrier'
    DEBRIS = 'debris'
    DITCH = 'ditch'
    ENTRANCE = 'entrance'
    FENCE = 'fence'
    FULL_HEIGHT_TURNSTILE = 'full-height_turnstile'
    GATE = 'gate'
    GUARD_RAIL = 'guard_rail'
    HAMPSHIRE_GATE = 'hampshire_gate'
    HANDRAIL = 'handrail'
    HEDGE = 'hedge'
    HEIGHT_RESTRICTOR = 'height_restrictor'
    HORSE_STILE = 'horse_stile'
    JERSEY_BARRIER = 'jersey_barrier'
    KERB = 'kerb'
    KISSING_GATE = 'kissing_gate'
    LIFT_GATE = 'lift_gate'
    LOG = 'log'
    MOTORCYCLE_BARRIER = 'motorcycle_barrier'
    RETAINING_WALL = 'retaining_wall'
    ROPE = 'rope'
    SALLY_PORT = 'sally_port'
    SPIKES = 'spikes'
    STILE = 'stile'
    SUMP_BUSTER = 'sump_buster'
    SWING_GATE = 'swing_gate'
    TOLL_BOOTH = 'toll_booth'
    TURNSTILE = 'turnstile'
    WALL = 'wall'
    YES = 'yes'
