from core.enums.enum_str import EnumStr


class BuildingMaterial(EnumStr):
    # https://wiki.openstreetmap.org/wiki/Key:building:material
    ADOBE = 'adobe'
    BAMBOO = 'bamboo'
    BRICK = 'brick'
    CEMENT_BLOCK = 'cement_block'
    CLAY = 'clay'
    CONCRETE = 'concrete'
    COPPER = 'copper'
    GLASS = 'glass'
    LIMESTONE = 'limestone'
    LOAM = 'loam'
    MARBLE = 'marble'
    MASONRY = 'masonry'
    METAL = 'metal'
    METAL_PLATES = 'metal_plates'
    MIRROR = 'mirror'
    MUD = 'mud'
    PEBBLEDASH = 'pebbledash'
    PLASTER = 'plaster'
    PLASTIC = 'plastic'
    RAMMED_EARTH = 'rammed_earth'
    REED = 'reed'
    SANDSTONE = 'sandstone'
    SLATE = 'slate'
    SOLAR_PANELS = 'solar_panels'
    STEEL = 'steel'
    STONE = 'stone'
    TILES = 'tiles'
    TIMBER_FRAMING = 'timber_framing'
    TIN = 'tin'
    TYRES = 'tyres'
    VINYL = 'vinyl'
    WOOD = 'wood'
