from core.enums.enum_str import EnumStr


class Construction(EnumStr):
    # https://wiki.openstreetmap.org/wiki/Key:construction
    BRIDLEWAY = 'bridleway'
    CYCLEWAY = 'cycleway'
    FOOTWAY = 'footway'
    LIGHT_RAIL = 'light_rail'
    LIVING_STREET = 'living_street'
    MONORAIL = 'monorail'
    MOTORWAY = 'motorway'
    MOTORWAY_LINK = 'motorway_link'
    NARROW_GAUGE = 'narrow_gauge'
    PATH = 'path'
    PEDESTRIAN = 'pedestrian'
    PRESERVED = 'preserved'
    PRIMARY = 'primary'
    PRIMARY_LINK = 'primary_link'
    RACEWAY = 'raceway'
    RAIL = 'rail'
    RESIDENTIAL = 'residential'
    ROAD = 'road'
    SECONDARY = 'secondary'
    SECONDARY_LINK = 'secondary_link'
    SERVICE = 'service'
    STEPS = 'steps'
    SUBWAY = 'subway'
    TERTIARY = 'tertiary'
    TERTIARY_LINK = 'tertiary_link'
    TRACK = 'track'
    TRAM = 'tram'
    TRUNK = 'trunk'
    TRUNK_LINK = 'trunk_link'
    UNCLASSIFIED = 'unclassified'
