from core.enums.enum_str import EnumStr


class Hazard(EnumStr):
    # https://wiki.openstreetmap.org/wiki/Key:hazard
    ANIMAL_CROSSING = 'animal_crossing'
    ARCHERY_RANGE = 'archery_range'
    AVALANCHE = 'avalanche'
    BIOHAZARD = 'biohazard'
    BUMP = 'bump'
    CHILDREN = 'children'
    COLLAPSE = 'collapse'
    CONTAMINATION = 'contamination'
    CONTRAFLOW = 'contraflow'
    CURVE = 'curve'
    CURVES = 'curves'
    CYCLISTS = 'cyclists'
    DAMAGED_ROAD = 'damaged_road'
    DANGEROUS_JUNCTION = 'dangerous_junction'
    DIP = 'dip'
    ELECTRICITY = 'electricity'
    EMERGENCY_VEHICLES = 'emergency_vehicles'
    FALLING_ROCKS = 'falling_rocks'
    FALLING_TREES = 'falling_trees'
    FLOODING = 'flooding'
    FOG = 'fog'
    FRAIL_PEDESTRIANS = 'frail_pedestrians'
    FROST_HEAVE = 'frost_heave'
    GROUND_CLEARANCE = 'ground_clearance'
    HOLE = 'hole'
    HORSE_RIDERS = 'horse_riders'
    ICE = 'ice'
    ILLEGAL_CROSSING = 'illegal_crossing'
    LANDSLIDE = 'landslide'
    LEECHES = 'leeches'
    LOOSE_GRAVEL = 'loose_gravel'
    LOW_FLYING_AIRCRAFT = 'low_flying_aircraft'
    MINEFIELD = 'minefield'
    NUCLEAR = 'nuclear'
    PEDESTRIAN_CROSSING = 'pedestrian_crossing'
    PEDESTRIANS = 'pedestrians'
    QUEUES_LIKELY = 'queues_likely'
    QUICKSAND = 'quicksand'
    ROAD_NARROWS = 'road_narrows'
    ROADWORKS = 'roadworks'
    ROUNDABOUT = 'roundabout'
    SCHOOL_ZONE = 'school_zone'
    SHOOTING_RANGE = 'shooting_range'
    SIDE_WINDS = 'side_winds'
    SILVER_ZONE = 'silver_zone'
    SLIPPERY = 'slippery'
    TIDE = 'tide'
    TRAFFIC_SIGNALS = 'traffic_signals'
    TURN = 'turn'
    TURNS = 'turns'
    UNEXPLODED_ORDNANCE = 'unexploded_ordnance'
    WASHOUT = 'washout'
