from core.enums.enum_str import EnumStr


class Landuse(EnumStr):
    # https://wiki.openstreetmap.org/wiki/Key:landuse
    ALLOTMENTS = 'allotments'
    ANIMAL_KEEPING = 'animal_keeping'
    AQUACULTURE = 'aquaculture'
    BASIN = 'basin'
    BROWNFIELD = 'brownfield'
    CEMETERY = 'cemetery'
    CIVIC_ADMIN = 'civic_admin'
    COMMERCIAL = 'commercial'
    CONSERVATION = 'conservation'
    CONSTRUCTION = 'construction'
    DEPOT = 'depot'
    EDUCATION = 'education'
    FAIRGROUND = 'fairground'
    FARMLAND = 'farmland'
    FARMYARD = 'farmyard'
    FLOWERBED = 'flowerbed'
    FOREST = 'forest'
    GARAGES = 'garages'
    GRASS = 'grass'
    GREENERY = 'greenery'
    GREENFIELD = 'greenfield'
    GREENHOUSE_HORTICULTURE = 'greenhouse_horticulture'
    HIGHWAY = 'highway'
    INDUSTRIAL = 'industrial'
    INSTITUTIONAL = 'institutional'
    LANDFILL = 'landfill'
    LOGGING = 'logging'
    MEADOW = 'meadow'
    MILITARY = 'military'
    ORCHARD = 'orchard'
    PLANT_NURSERY = 'plant_nursery'
    PORT = 'port'
    QUARRY = 'quarry'
    RAILWAY = 'railway'
    RECREATION_GROUND = 'recreation_ground'
    RELIGIOUS = 'religious'
    RESERVOIR = 'reservoir'
    RESIDENTIAL = 'residential'
    RETAIL = 'retail'
    SALT_POND = 'salt_pond'
    VILLAGE_GREEN = 'village_green'
    VINEYARD = 'vineyard'
    WINTER_SPORTS = 'winter_sports'
