from core.enums.enum_str import EnumStr


class Leisure(EnumStr):
    # https://wiki.openstreetmap.org/wiki/Key:leisure
    ADULT_GAMING_CENTRE = 'adult_gaming_centre'
    AMUSEMENT_ARCADE = 'amusement_arcade'
    BANDSTAND = 'bandstand'
    BEACH_RESORT = 'beach_resort'
    BIRD_HIDE = 'bird_hide'
    BOWLING_ALLEY = 'bowling_alley'
    COMMON = 'common'
    DANCE = 'dance'
    DISC_GOLF_COURSE = 'disc_golf_course'
    DOG_PARK = 'dog_park'
    ESCAPE_GAME = 'escape_game'
    FIREPIT = 'firepit'
    FISHING = 'fishing'
    FITNESS_CENTRE = 'fitness_centre'
    FITNESS_STATION = 'fitness_station'
    GARDEN = 'garden'
    GOLF_COURSE = 'golf_course'
    HACKERSPACE = 'hackerspace'
    HORSE_RIDING = 'horse_riding'
    ICE_RINK = 'ice_rink'
    MARINA = 'marina'
    MINIATURE_GOLF = 'miniature_golf'
    NATURE_RESERVE = 'nature_reserve'
    OUTDOOR_SEATING = 'outdoor_seating'
    PADDLING_POOL = 'paddling_pool'
    PARK = 'park'
    PICNIC_TABLE = 'picnic_table'
    PITCH = 'pitch'
    PLAYGROUND = 'playground'
    SAUNA = 'sauna'
    SLIPWAY = 'slipway'
    SPORTS_CENTRE = 'sports_centre'
    STADIUM = 'stadium'
    SUMMER_CAMP = 'summer_camp'
    SWIMMING_AREA = 'swimming_area'
    SWIMMING_POOL = 'swimming_pool'
    TRACK = 'track'
    WATER_PARK = 'water_park'
