from core.enums.enum_str import EnumStr


class Natural(EnumStr):
    # https://wiki.openstreetmap.org/wiki/Key:natural
    ARCH = 'arch'
    ARETE = 'arete'
    BARE_ROCK = 'bare_rock'
    BAY = 'bay'
    BEACH = 'beach'
    BLOCKFIELD = 'blockfield'
    BLOWHOLE = 'blowhole'
    CAPE = 'cape'
    CAVE_ENTRANCE = 'cave_entrance'
    CLIFF = 'cliff'
    COASTLINE = 'coastline'
    CREVASSE = 'crevasse'
    DUNE = 'dune'
    EARTH_BANK = 'earth_bank'
    FELL = 'fell'
    FUMAROLE = 'fumarole'
    GEYSER = 'geyser'
    GLACIER = 'glacier'
    GRASSLAND = 'grassland'
    HEATH = 'heath'
    HILL = 'hill'
    HOT_SPRING = 'hot_spring'
    ISTHMUS = 'isthmus'
    MOOR = 'moor'
    MUD = 'mud'
    PEAK = 'peak'
    PENINSULA = 'peninsula'
    REEF = 'reef'
    RIDGE = 'ridge'
    ROCK = 'rock'
    SADDLE = 'saddle'
    SAND = 'sand'
    SCREE = 'scree'
    SCRUB = 'scrub'
    SHINGLE = 'shingle'
    SHOAL = 'shoal'
    SHRUBBERY = 'shrubbery'
    SINKHOLE = 'sinkhole'
    SPRING = 'spring'
    STONE = 'stone'
    STRAIT = 'strait'
    TREE = 'tree'
    TREE_ROW = 'tree_row'
    TUNDRA = 'tundra'
    VALLEY = 'valley'
    VOLCANO = 'volcano'
    WATER = 'water'
    WETLAND = 'wetland'
    WOOD = 'wood'
