from core.enums.enum_str import EnumStr


class Place(EnumStr):
    # https://wiki.openstreetmap.org/wiki/Key:place
    ALLOTMENTS = 'allotments'
    ARCHIPELAGO = 'archipelago'
    BOROUGH = 'borough'
    CITY = 'city'
    CITY_BLOCK = 'city_block'
    CONTINENT = 'continent'
    COUNTRY = 'country'
    COUNTY = 'county'
    DISTRICT = 'district'
    FARM = 'farm'
    HAMLET = 'hamlet'
    ISLAND = 'island'
    ISLET = 'islet'
    ISOLATED_DWELLING = 'isolated_dwelling'
    LOCALITY = 'locality'
    MUNICIPALITY = 'municipality'
    NEIGHBOURHOOD = 'neighbourhood'
    OCEAN = 'ocean'
    PLOT = 'plot'
    POLDER = 'polder'
    PROVINCE = 'province'
    QUARTER = 'quarter'
    REGION = 'region'
    SEA = 'sea'
    SQUARE = 'square'
    STATE = 'state'
    SUBDISTRICT = 'subdistrict'
    SUBURB = 'suburb'
    TOWN = 'town'
    VILLAGE = 'village'
