from core.enums.enum_str import EnumStr


class Railway(EnumStr):
    # https://wiki.openstreetmap.org/wiki/Key:railway
    ABANDONED = 'abandoned'
    BUFFER_STOP = 'buffer_stop'
    CONSTRUCTION = 'construction'
    CROSSING = 'crossing'
    DERAIL = 'derail'
    DISUSED = 'disused'
    FUNICULAR = 'funicular'
    HALT = 'halt'
    LEVEL_CROSSING = 'level_crossing'
    LIGHT_RAIL = 'light_rail'
    MINIATURE = 'miniature'
    MONORAIL = 'monorail'
    NARROW_GAUGE = 'narrow_gauge'
    PLATFORM = 'platform'
    PRESERVED = 'preserved'
    PROPOSED = 'proposed'
    RAIL = 'rail'
    RAILWAY_CROSSING = 'railway_crossing'
    ROUNDHOUSE = 'roundhouse'
    SIGNAL = 'signal'
    STATION = 'station'
    STOP = 'stop'
    SUBWAY = 'subway'
    SUBWAY_ENTRANCE = 'subway_entrance'
    SWITCH = 'switch'
    TRAM = 'tram'
    TRAM_LEVEL_CROSSING = 'tram_level_crossing'
    TRAM_STOP = 'tram_stop'
    TRAVERSER = 'traverser'
    TURNTABLE = 'turntable'
    VENTILATION_SHAFT = 'ventilation_shaft'
    WASH = 'wash'
    WATER_CRANE = 'water_crane'
    WORKSHOP = 'workshop'
