from core.enums.enum_str import EnumStr


class Substance(EnumStr):
    # https://wiki.openstreetmap.org/wiki/Key:substance
    ACETONE = 'acetone'
    ACRYLONITRILE = 'acrylonitrile'
    AMMONIA = 'ammonia'
    BENZENE = 'benzene'
    BRINE = 'brine'
    BUTADIENE = 'butadiene'
    BUTANE = 'butane'
    BUTENE = 'butene'
    CARBON_DIOXIDE = 'carbon_dioxide'
    CARBON_MONOXIDE = 'carbon_monoxide'
    CHEMICALS = 'chemicals'
    CHLORINE = 'chlorine'
    CUMENE = 'cumene'
    CYCLOHEXANE = 'cyclohexane'
    DECENE = 'decene'
    ETHANE = 'ethane'
    ETHYLBENZENE = 'ethylbenzene'
    ETHYLENE = 'ethylene'
    FUEL = 'fuel'
    GAS = 'gas'
    HEXANE = 'hexane'
    HEXENE = 'hexene'
    HOT_WATER = 'hot_water'
    HYDROGEN = 'hydrogen'
    ISOBUTANE = 'isobutane'
    ISOBUTYLENE = 'isobutylene'
    ISOPENTANE = 'isopentane'
    ISOPRENE = 'isoprene'
    LNG = 'lng'
    LPG = 'lpg'
    METHANE = 'methane'
    METHANOL = 'methanol'
    NAPHTHA = 'naphtha'
    NGL = 'ngl'
    NITROGEN = 'nitrogen'
    OCTENE = 'octene'
    OIL = 'oil'
    OXYGEN = 'oxygen'
    PENTANE = 'pentane'
    POLYPROPYLENE = 'polypropylene'
    PROPANE = 'propane'
    PROPYLENE = 'propylene'
    RAINWATER = 'rainwater'
    SEWAGE = 'sewage'
    SLURRY = 'slurry'
    STEAM = 'steam'
    TOLUENE = 'toluene'
    WATER = 'water'
    XYLENE = 'xylene'
    Y_GRADE = 'y-grade'
