from core.enums.enum_str import EnumStr


class Surface(EnumStr):
    # https://wiki.openstreetmap.org/wiki/Key:surface
    ACRYLIC = 'acrylic'
    ARTIFICIAL_TURF = 'artificial_turf'
    ASPHALT = 'asphalt'
    BRICKS = 'bricks'
    CARPET = 'carpet'
    CHIPSEAL = 'chipseal'
    CLAY = 'clay'
    COBBLESTONE = 'cobblestone'
    COBBLESTONE_FLATTENED = 'cobblestone:flattened'
    COMPACTED = 'compacted'
    CONCRETE = 'concrete'
    CONCRETE_LANES = 'concrete:lanes'
    CONCRETE_PLATES = 'concrete:plates'
    DIRT = 'dirt'
    EARTH = 'earth'
    FIBRE_REINFORCED_POLYMER_GRATE = 'fibre_reinforced_polymer_grate'
    FINE_GRAVEL = 'fine_gravel'
    GRASS = 'grass'
    GRASS_PAVER = 'grass_paver'
    GRAVEL = 'gravel'
    GROUND = 'ground'
    ICE = 'ice'
    LATERITE = 'laterite'
    METAL = 'metal'
    METAL_GRID = 'metal_grid'
    MUD = 'mud'
    PAVED = 'paved'
    PAVING_STONES = 'paving_stones'
    PAVING_STONES_LANES = 'paving_stones:lanes'
    PEBBLESTONE = 'pebblestone'
    PLASTIC = 'plastic'
    ROCK = 'rock'
    RUBBER = 'rubber'
    SALT = 'salt'
    SAND = 'sand'
    SETT = 'sett'
    SHELLS = 'shells'
    SNOW = 'snow'
    STEPPING_STONES = 'stepping_stones'
    TARTAN = 'tartan'
    TILES = 'tiles'
    UNHEWN_COBBLESTONE = 'unhewn_cobblestone'
    UNPAVED = 'unpaved'
    WOOD = 'wood'
    WOODCHIPS = 'woodchips'
