from core.enums.enum_str import EnumStr


class CurrencyCodes(EnumStr):
    ALBANIAN_LEK = 'ALL'
    BELARUSIAN_RUBLE = 'BYN'
    BOSNIA_AND_HERZEGOVINA_CONVERTIBLE_MARK = 'BAM'
    BULGARIAN_LEV = 'BGN'
    CZECH_KORUNA = 'CZK'
    DANISH_KRONE = 'DKK'
    EURO = 'EUR'
    HUNGARIAN_FORINT = 'HUF'
    ICELANDIC_KRONA = 'ISK'
    MACEDONIAN_DENAR = 'MKD'
    MOLDOVAN_LEU = 'MDL'
    NORWEGIAN_KRONE = 'NOK'
    POLISH_ZLOTY = 'PLN'
    ROMANIAN_LEU = 'RON'
    SERBIAN_DINAR = 'RSD'
    STERLING = 'GBP'
    SWEDISH_KRONA = 'SEK'
    SWISS_FRANC = 'CHF'
    TURKISH_LIRA = 'TRY'
    UKRAINIAN_HRYVNIA = 'UAH'
